### PR TITLE
Documentation: Include a history of UMD and when/why to use it

### PR DESCRIPTION
**Pull request by DanKaplanSES**
- This information is from @bergus and their answer to the question, "What is the Universal Module Definition (UMD)?": https://stackoverflow.com/a/77284527/61624 The linked question explains the motivation for this addition.
- See issue https://github.com/umdjs/umd/issues/143

### CODE REVIEW

**Comment by DanKaplanSES** [comment]
@addyosmani / @EvanCarroll : Hello! Sorry for the ping, but I was wondering if I could receive feedback on my PR? 

Thanks!

PS: If I can help in anyway, I'd be interested in reviewing the other issues and PRs of the repository. How would one go about getting write access?

**Review by TheGiraffe3 — APPROVED** [review]

**Comment by TheGiraffe3** [comment]
You don't need to have write access to review pull requests; as I did above; but to merge them you do need access.

**Comment by TheGiraffe3** [comment]
@addyosmani you've been active elsewhere, could you please review this?

**Comment by addyosmani** [comment]
Hey folks. After reading through this LGTM. I'll go ahead and merge it.

**Pull request merged**
