### PR TITLE
Add jshint & npm test script

### PR DESCRIPTION
**Pull request by adjohnson916**
Adding JSHint via Grunt, and npm test script.

This will help ensure we have valid and safe JS, especially through proposed changes.

Once this is in place, we can get CI integration and badges, e.g. Travis CI.

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks for the PR. Given that we're just looking at linting here, can you replace the Grunt setup with a straight npm script?

**Comment by arthurvr** [comment]
ping @adjohnson916 :)

**Comment by adjohnson916** [comment]
@addyosmani @arthurvr I've switched this to a simple npm script using vanilla jshint as a dependency, removing the grunt file and dependency.

I've rebased the same branch and force pushed, though its name which includes "grunt" is now a misnomer, rather then create a new branch and PR, because it keeps things together better.

Note that there are JSHint warnings in the current code. If we merge this, I can follow up with fixes for that. Would you then consider adding CI to check this, e.g. Travis CI?

**Comment by adjohnson916** [comment]
@EvanCarroll Thanks for merging!

**Comment by EvanCarroll** [comment]
NP. patches will be easier to get in now. I'm going to help out with the project. Thank for the patience.

**Pull request merged**
