### PR TITLE
Check object structure to guard against global pollution from HTMLElements

### PR DESCRIPTION
**Pull request by mikesherov**

### CODE REVIEW

**Comment by arthurvr** [comment]
I like this. Fixes #35, right?

**Comment by mikesherov** [comment]
@arthurvr check the full commit message ;-)

**Comment by arthurvr** [comment]
@mikesherov Whoops :) Yep! :smile:

**Comment by addyosmani** [comment]
LGTM. Thanks for writing the patch. Will wait for a second LGTM from @jrburke in case he has further comments before landing.

**Comment by mikesherov** [comment]
Thanks for the review @addyosmani!

**Comment by jrburke** [comment]
LGTM

**Comment by mikesherov** [comment]
Thanks @jrburke! Safe to land :-)

**Comment by addyosmani** [comment]
Landed. Thanks again, Mike!

**Pull request merged**
