### PR TITLE
Fix bad line break per JSHint. See #57.

### PR DESCRIPTION
**Pull request by adjohnson916**
See #57. Replaces #58.

### CODE REVIEW

**Comment by EvanCarroll** [comment]
Why is this not closed if it was merged?

**Comment by adjohnson916** [comment]
@EvanCarroll Was this merged? I didn't think so.

**Comment by EvanCarroll** [comment]
No it wasn't I didn't realize you weren't developing on master. I did however merge your two pull requests into my branch. Good job. We need to consider forking this module. It isn't getting any :heart: .

**Comment by adjohnson916** [comment]
@EvanCarroll Thanks for merging!

**Pull request merged**
